name: Lint & Test

on:
  pull_request:
    branches: [s3_branch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - run: pip install ruff
      - run: ruff check --fix .

  tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - run: pip install pytest
      - run: pip install -r requirements.txt
      - run: pytest

